version: '3.8'

services:
  llm:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./Cache:/app/Cache
      - ./Kapweb:/app/Kapweb
      - ./models.json:/app/models.json
      - ./Services/llm.py:/app/server.py
      - ./Services/llm.requirements.txt:/app/requirements.txt
    ports:
      - "10000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    entrypoint: >
        /bin/sh -c "
        apt-get update &&
        apt-get install -y build-essential cmake &&
        rm -rf /var/lib/apt/lists/* &&
        pip install --no-cache-dir -r /app/requirements.txt &&
        uvicorn server:app --host 0.0.0.0 --port 8000
        "

  image_service:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./Cache:/app/Cache
      - ./Kapweb:/app/Kapweb
      - ./image_models.json:/app/image_models.json
      - ./Services/image.py:/app/server.py
      - ./Services/image.requirements.txt:/app/requirements.txt
    ports:
      - "10001:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    entrypoint: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y build-essential cmake tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng &&
      rm -rf /var/lib/apt/lists/* &&
      pip install --no-cache-dir -r /app/requirements.txt &&
      uvicorn server:app --host 0.0.0.0 --port 8000
      "

  translation:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./Cache:/app/Cache
      - ./Kapweb:/app/Kapweb
      - ./Services/translation.py:/app/server.py
      - ./Services/translation.requirements.txt:/app/requirements.txt
    ports:
      - "10002:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    entrypoint: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y build-essential cmake &&
      rm -rf /var/lib/apt/lists/* &&
      pip install --no-cache-dir -r /app/requirements.txt &&
      uvicorn server:app --host 0.0.0.0 --port 8000
      "
  
  speech:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./Cache:/app/Cache
      - ./Kapweb:/app/Kapweb
      - ./Services/speech.py:/app/server.py
      - ./Services/speech.requirements.txt:/app/requirements.txt
    ports:
      - "10003:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - COQUI_TOS_AGREED=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    entrypoint: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y build-essential cmake curl libsndfile1 &&
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
      PATH="/root/.cargo/bin:${PATH}" &&
      rm -rf /var/lib/apt/lists/* &&
      pip install --no-cache-dir -r /app/requirements.txt &&
      uvicorn server:app --host 0.0.0.0 --port 8000
      "
  
  media:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./Cache:/app/Cache
      - ./Kapweb:/app/Kapweb
      - ./image_models.json:/app/image_models.json
      - ./Services/media.py:/app/server.py
      - ./Services/media.requirements.txt:/app/requirements.txt
    ports:
      - "10004:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    entrypoint: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y build-essential cmake &&
      rm -rf /var/lib/apt/lists/* &&
      pip install --no-cache-dir -r /app/requirements.txt &&
      uvicorn server:app --host 0.0.0.0 --port 8000
      "
  
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cors.conf:/etc/nginx/cors.conf:ro
    depends_on:
      - llm
      - image_service
      - translation
      - speech
      - media

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: